package cz.kamosh.multiindex.test;
import cz.kamosh.multiindex.interf.Indexable;

/**
 * Do not edit this file. It is generated using generator
 * {@link cz.kamosh.multiindex.annotation.MultiIndexContainerGenerator}
 * based on annotated file {@link cz.kamosh.multiindex.test.Person}
 */
public enum Person_Indexes implements Indexable<cz.kamosh.multiindex.test.Person> {

    Surname {
        public Object getIndexedValue(cz.kamosh.multiindex.test.Person record) {
              return record.getSurname();
        }
    },
    BmiIndex {
        public Object getIndexedValue(cz.kamosh.multiindex.test.Person record) {
              return record.getBmiIndex();
        }
    },
    Name {
        public Object getIndexedValue(cz.kamosh.multiindex.test.Person record) {
              return record.getName();
        }
    },
    Man {
        public Object getIndexedValue(cz.kamosh.multiindex.test.Person record) {
              return record.isMan();
        }
    },
    BirthYear {
        public Object getIndexedValue(cz.kamosh.multiindex.test.Person record) {
              return record.getBirthYear();
        }
    },
}